"""Adding document and documnet chunk table

Revision ID: 7e0296d1a4d8
Revises: e699239da955
Create Date: 2026-07-15 13:47:57.058817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7e0296d1a4d8'
down_revision: Union[str, Sequence[str], None] = 'e699239da955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('DocID', sa.Integer(), nullable=False),
    sa.Column('DocTitle', sa.String(), nullable=False),
    sa.Column('DocName', sa.String(), nullable=False),
    sa.Column('DocCreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('DocID')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_DocID'), ['DocID'], unique=False)

    op.create_table('document_chunks',
    sa.Column('ChunkID', sa.Integer(), nullable=False),
    sa.Column('DocumentID', sa.Integer(), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('Embedding', Vector(dim=1024), nullable=False),
    sa.Column('ChunkIndex', sa.Integer(), nullable=False),
    sa.Column('Metadata', sa.JSON(), nullable=True),
    sa.Column('ChunkCreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['DocumentID'], ['documents.DocID'], ),
    sa.PrimaryKeyConstraint('ChunkID')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_ChunkID'), ['ChunkID'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_ChunkID'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_DocID'))

    op.drop_table('documents')
    # ### end Alembic commands ###
