"""change embedding dimension

Revision ID: 8dfc8c799845
Revises: 98e3fd742e6b
Create Date: 2026-07-18 13:47:48.672878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '8dfc8c799845'
down_revision: Union[str, Sequence[str], None] = '98e3fd742e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.alter_column('Embedding',
               existing_type=Vector(dim=256),
               type_=Vector(dim=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.alter_column('Embedding',
               existing_type=Vector(dim=512),
               type_=Vector(dim=256),
               existing_nullable=False)

    # ### end Alembic commands ###
