"""initialize database setup

Revision ID: 921f5f104460
Revises: 
Create Date: 2026-07-07 14:49:28.296757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921f5f104460'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Intent',
    sa.Column('IntentID', sa.Integer(), nullable=False),
    sa.Column('IntentName', sa.String(), nullable=False),
    sa.Column('IntentDiscription', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('IntentID'),
    sa.UniqueConstraint('IntentName')
    )
    with op.batch_alter_table('Intent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Intent_IntentID'), ['IntentID'], unique=False)

    op.create_table('User',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(), nullable=False),
    sa.Column('UserEmail', sa.String(), nullable=False),
    sa.Column('UserPass', sa.String(), nullable=False),
    sa.Column('UserRole', sa.String(), nullable=True),
    sa.Column('UserCreationDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('UserEmail'),
    sa.UniqueConstraint('UserName')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User_UserID'), ['UserID'], unique=False)

    op.create_table('Conversation',
    sa.Column('ConversationID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('ConversationTitle', sa.String(), nullable=False),
    sa.Column('ConversationDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ),
    sa.PrimaryKeyConstraint('ConversationID')
    )
    with op.batch_alter_table('Conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Conversation_ConversationID'), ['ConversationID'], unique=False)

    op.create_table('Phrase',
    sa.Column('PhraseID', sa.Integer(), nullable=False),
    sa.Column('IntentID', sa.Integer(), nullable=False),
    sa.Column('PhraseText', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['IntentID'], ['Intent.IntentID'], ),
    sa.PrimaryKeyConstraint('PhraseID')
    )
    with op.batch_alter_table('Phrase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Phrase_PhraseID'), ['PhraseID'], unique=False)

    op.create_table('Response',
    sa.Column('ResponseID', sa.Integer(), nullable=False),
    sa.Column('IntentID', sa.Integer(), nullable=False),
    sa.Column('ResponseText', sa.String(), nullable=False),
    sa.Column('ResponseAccessLevel', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['IntentID'], ['Intent.IntentID'], ),
    sa.PrimaryKeyConstraint('ResponseID')
    )
    with op.batch_alter_table('Response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Response_ResponseID'), ['ResponseID'], unique=False)

    op.create_table('Message',
    sa.Column('MessageID', sa.Integer(), nullable=False),
    sa.Column('ConversationID', sa.Integer(), nullable=False),
    sa.Column('MessageSender', sa.String(), nullable=False),
    sa.Column('MessageText', sa.Text(), nullable=False),
    sa.Column('MessageDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ConversationID'], ['Conversation.ConversationID'], ),
    sa.PrimaryKeyConstraint('MessageID')
    )
    with op.batch_alter_table('Message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Message_MessageID'), ['MessageID'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Message_MessageID'))

    op.drop_table('Message')
    with op.batch_alter_table('Response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Response_ResponseID'))

    op.drop_table('Response')
    with op.batch_alter_table('Phrase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Phrase_PhraseID'))

    op.drop_table('Phrase')
    with op.batch_alter_table('Conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Conversation_ConversationID'))

    op.drop_table('Conversation')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_UserID'))

    op.drop_table('User')
    with op.batch_alter_table('Intent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Intent_IntentID'))

    op.drop_table('Intent')
    # ### end Alembic commands ###
