"""change embedding dimension

Revision ID: 98e3fd742e6b
Revises: 7e0296d1a4d8
Create Date: 2026-07-15 14:55:17.464572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '98e3fd742e6b'
down_revision: Union[str, Sequence[str], None] = '7e0296d1a4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.alter_column('Embedding',
               existing_type=Vector(dim=1024),
               type_=Vector(dim=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.alter_column('Embedding',
               existing_type=Vector(dim=256),
               type_=Vector(dim=1024),
               existing_nullable=False)

    # ### end Alembic commands ###
