"""add conversation summary table

Revision ID: ea4551e3d1f7
Revises: 921f5f104460
Create Date: 2026-07-12 17:38:04.992043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4551e3d1f7'
down_revision: Union[str, Sequence[str], None] = '921f5f104460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Summary',
    sa.Column('SummaryID', sa.Integer(), nullable=False),
    sa.Column('ConversationID', sa.Integer(), nullable=False),
    sa.Column('SummaryText', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ConversationID'], ['Conversation.ConversationID'], ),
    sa.PrimaryKeyConstraint('SummaryID')
    )
    with op.batch_alter_table('Summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Summary_SummaryID'), ['SummaryID'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Summary_SummaryID'))

    op.drop_table('Summary')
    # ### end Alembic commands ###
