"""Summary table Upgraded

Revision ID: fa5d488e605f
Revises: 73c20ced729b
Create Date: 2026-07-14 12:27:38.036763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5d488e605f'
down_revision: Union[str, Sequence[str], None] = '73c20ced729b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('StartMsg', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('EndMsg', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('SummaryDate', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'Message', ['EndMsg'], ['MessageID'])
        batch_op.create_foreign_key(None, 'Message', ['StartMsg'], ['MessageID'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Summary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('SummaryDate')
        batch_op.drop_column('EndMsg')
        batch_op.drop_column('StartMsg')

    # ### end Alembic commands ###
